title:               whitekr0w's Blog
url:                 ""
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /archive/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              ''
  url:               ''
  email:             ''

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist